#version: '3.8'

services:
  app:
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"  # Exponer el puerto 9000 para que Nginx lo pueda usar

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
volumes:
  db_data:
